language: node_js
node_js:
  - 'lts/*'
branches:
  only:
    - blog

before_script:
  - npm install -g hexo

script:
  - npm run start
  - npm run index

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master
  local-dir: public

cache:
  directories:
    - node_modules
